
{"word": "", "translate": "", "tutor": "Luk", "date": "27.04,2019", "category": "word"},
SAMPLE_DATA = {
    {"word":"preciding","translate":"poprzedzający", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"flyers","translate":"ulotki", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"flyers","translate":"ulotki", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"leaflet","translate":"ulotki", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"drawer","translate":"szuflada", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"meanness","translate":"podłość", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"accusing","translate":"oskarżać", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"evict","translate":"eksmitować", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"infestation","translate":"plaga", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"acquire","translate":"pozyskać", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"gain","translate":"zyskać", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"heap","translate":"sterta", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"pile","translate":"stos", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"mere","translate":"wyłączny", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"commander","translate":"dowódca", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},
    {"word":"council","translate":"rada miasta", "tutor":"Piotr", "date":"06.04,2019", "category": "word"},


    {"word":"suffer","translate":"cierpieć", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"antsy","translate":"nerwowy", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"ograniczony","translate":"scarce", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"scribe","translate":"mazać", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"spewing","translate":"wymiotowanie", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"exacerbate","translate":"zaostrzać", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"overcome","translate":"przezwycięzyć", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"defeated","translate":"przegrany", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"tackle","translate":"zaatakować", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word": "bring up", "translate": "podnosić cos", "tutor": "Luk", "date": "01.04,2019", "category": "word"},
    {"word":"insoluble","translate":"nierozpuszczalny", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"urgent","translate":"pilny", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"immediatly","translate":"pilny", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"major","translate":"wiekszosc", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"minor","translate":"mnijeszosc", "tutor":"Luk", "date":"01.04,2019", "category": "word"},
    {"word":"tipsy","translate":"wstawiony", "tutor":"Piotr", "date":"27.04,2019", "category": "word"},
    {"word":"vomit","translate":"wymioty", "tutor":"Piotr", "date":"27.04,2019", "category": "word"},
    {"word":"testicle","translate":"meskie jądra", "tutor":"Piotr", "date":"27.04,2019", "category": "word"},
    {"word":"burf","translate":"wymioty", "tutor":"Piotr", "date":"27.04,2019", "category": "word"},
    {"word":"puke","translate":"wymioty", "tutor":"Piotr", "date":"27.04,2019", "category": "word"},
    {"word":"leave pavement pizza","translate":"zwymiotowac", "tutor":"Piotr", "date":"27.04,2019", "category": "word"},
    {"word":"obsticle","translate":"przeszkoda", "tutor":"Piotr", "date":"27.04,2019", "category": "word"},
    {"word":"abuse","translate":"naduzycie", "tutor":"Luk", "date":"27.04,2019", "category": "word"},
    {"word":"sanitary issue","translate":"podpaska", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"booger","translate":"koza z nosa", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"prone to","translate":"podatny na(choroby)", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"pick the nose","translate":"dłubac w nosie", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"from time to time","translate":"od czasu do czasu", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"make friends","translate":"zaprzjażniać sie", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"do firends","translate":"zaliczac przyjaciół", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"unigue","translate":"uniqalny", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"eunuch","translate":"kastrat", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"gradual","translate":"stopniowy", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"little","translate":"mało", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"a little","translate":"tak troche", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"on time","translate":"na czas", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"in time","translate":"wczesniej", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"give up","translate":"poddac sie", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"give in","translate":"uleć", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"epiphany","translate":"olsnienie", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"disguise","translate":"przebranie", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"skyline","translate":"horyzont", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"rought idea","translate":"mgliste pojecie", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"apparent","translate":"wyraźna", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"I'll sort ","translate":"zajmę się", "tutor":"Piotr", "date":"01.04,2019", "category": "word"},
    {"word":"be bound to","translate":"przeznaczenie", "tutor":"Piotr", "date":"01.04,2019", "category": "sentence"},
    {"word": "inside out", "translate": "lewa na prawo", "tutor": "Piotr", "date": "01.04,2019", "category": "word"},
    {"word": "back to front", "translate": "tylem na przód", "tutor": "Piotr", "date": "01.04,2019", "category": "word"},
    {"word": "upside down", "translate": "do góry nogami", "tutor": "Piotr", "date": "01.04,2019", "category": "word"},
    {"word": "grip of it", "translate": "złapać kontekst", "tutor": "Piotr", "date": "01.04,2019", "category": "word"},
    {"word": "cottege", "translate": "domek wiesjski", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "skimp on", "translate": "skąpić", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "assume", "translate": "przypuszczac", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "frankly", "translate": "szczery, bez ogródek", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "down the line", "translate": "coś w przyszłosci", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "of the chart", "translate": "wiecej niż sie spodziewałem", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "splurge", "translate": "przepuszczać pieniądze", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "loosen up", "translate": "rozlużniac sie", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "pine three", "translate": "drzewo iglaste", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "leafy three", "translate": "drzewo lisciaste", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "pamper", "translate": "rozpieszczac", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
    {"word": "willingly", "translate": "chcąco", "tutor": "Luk", "date": "30.03,2019", "category": "word"},
    {"word": "as long as", "translate": "dopuki", "tutor": "Luk", "date": "30.03,2019", "category": "word"},
    {"word": "reek", "translate": "smród", "tutor": "Luk", "date": "30.03,2019", "category": "word"},
    {"word": "repulsive", "translate": "odpychający", "tutor": "Luk", "date": "30.03,2019", "category": "word"},
    {"word": "milking sth", "translate": "brać ile sie da", "tutor": "Luk", "date": "30.03,2019", "category": "word"},
    {"word": "in order", "translate": "w kolejności", "tutor": "Luk", "date": "30.03,2019", "category": "word"},
    {"word": "peak", "translate": "szczyt", "tutor": "Luk", "date": "30.03,2019", "category": "word"},
    {"word": "peek", "translate": "rzut oka", "tutor": "Luk", "date": "30.03,2019", "category": "word"},
    {"word": "", "translate": "", "tutor": "Luk", "date": "30.03,2019", "category": "word"},




    {"word":"I love to but I can't","translate":"bardzo bym chciał ale nie moge", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"I hate to miss out","translate":"bardzo załuje ze nie moge ", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"figger crossed","translate":"palce skrzyżowane na szczescie", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"you got this","translate":"dasz rade", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"what came up?","translate":"co sie stało? co ci wypadło?", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"sth come up","translate":"coś mi wyskoczyło", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"no biggie","translate":"no big deal", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"no worries","translate":"nie przejmuj sie", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"don't sweat it","translate":"nie przejmuj sie", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"reschedule","translate":"zmienić date", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"postpone","translate":"przełozyc", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"raincheck","translate":"dług", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"you own me","translate":"jestes mi dłuzny", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"I can;t make it","translate":"nie dam rady dzis", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"can we put it of","translate":"czy mozemy to odłozyć", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"If I had the choice","translate":"gdybym miał wybór", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"If I had choose","translate":"Gdybym musiał wybierać ", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"up my alley","translate":"po drodze mi z tym", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"wink wink","translate":"puscić oczo", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"resort to doing something","translate":"byc zmuszonemu do zrobienia czegos", "tutor":"Luk", "date":"22.04,2019", "category": "sentence"},
    {"word":"resorted","translate":"ostatnie wyjscie", "tutor":"Luk", "date":"22.04,2019", "category": "word"},

    {"word": "", "translate": "", "tutor": "Luk", "date": "22.04,2019", "category": "sentence"},

    {"word":"raise an issue","translate":"poruszyć problem", "tutor":"Luk", "date":"01.04,2019", "category": "sentence"},
    {"word":"address the problem","translate":"zająć sie problemem", "tutor":"Luk", "date":"01.04,2019", "category": "sentence"},
    {"word":"get to grip with sth","translate":"zaakceptować sytuaje", "tutor":"Luk", "date":"01.04,2019", "category": "sentence"},


    {"word":"get rid of","translate":"pozbyc sie", "tutor":"Piotr", "date":"06.04,2019", "category": "sentence"},
    {"word":"over the top","translate":"przesadzony", "tutor":"Piotr", "date":"06.04,2019", "category": "sentence"},
    {"word":"lets face it","translate":"spojrzmy prawdzie w oczy", "tutor":"Piotr", "date":"06.04,2019", "category": "sentence"},

    {"word":"fill up gas tank","translate":"zatankowac", "tutor":"Luk", "date":"30.03,2019", "category": "sentence"},
    {"word":"whatever float your boat","translate":"jak wollisz", "tutor":"Luk", "date":"30.03,2019", "category": "sentence"},
    {"word":"do you want catch a flick","translate":"czy chcesz skoczyc na film", "tutor":"Luk", "date":"30.03,2019", "category": "sentence"},
    {"word":"","translate":"", "tutor":"Luk", "date":"30.03,2019", "category": "sentence"},
    {"word":"","translate":"", "tutor":"Luk", "date":"30.03,2019", "category": "sentence"},
    {"word":"","translate":"", "tutor":"Luk", "date":"30.03,2019", "category": "sentence"},
}

{"word": "different strokes for different people", "translate": "weż sie w garść!", "tutor": "Luk",
 "date": "01.04,2019", "category": "sentence"},
{"word": "leaning towards", "translate": "", "tutor": "Luk", "date": "29.04,2019", "category": "word"},
{"word": "peek my interest", "translate": "", "tutor": "Luk", "date": "30.03,2019", "category": "sentence"},










