# Generated by Django 3.0.5 on 2020-04-19 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tutor', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
